version: "3"
services:

    db:
      image: mariadb:${MARIADB_VERSION}
      volumes:
        - "./.data/db:/var/lib/mysql"
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_HOST_PORT}:3306"

    php:
      build:
          context: .
          args:
              SRC: ${SYMFONY_APP_PATH}
              TIMEZONE: ${TIMEZONE}
              WORKDIR: ${SYMFONY_WORKING_DIR}
              COMPOSER_ALLOW_SUPERUSER: 1
#      working_dir: ${SYMFONY_WORKING_DIR}
      environment:
        - COMPOSER_ALLOW_SUPERUSER=1
      volumes:
        - ${SYMFONY_APP_PATH}:${SYMFONY_WORKING_DIR}
        - ./logs/symfony:${SYMFONY_WORKING_DIR}/var/logs
        - ./php.ini-development:/usr/local/etc/php/php.ini
      depends_on:
        - db

    nginx:
      build: config/nginx
      working_dir: ${SYMFONY_WORKING_DIR}
      volumes:
          - ${SYMFONY_APP_PATH}:${SYMFONY_WORKING_DIR}
          - ./logs/nginx/:/var/log/nginx
      ports:
          - "${NGINX_HOST_PORT}:80"
      depends_on:
          - php
